### PR TITLE
docker.io/hectorqin/reader

### PR DESCRIPTION
**Pull request by kongxiangyiren**
docker.io/hectorqin/reader

### CODE REVIEW

**Comment by kongxiangyiren** [comment]
> /auto-c

**Comment by wzshiming** [comment]
这个下面没找到源码和构建流程

还有个人提了相同的 org #13090

**Comment by kongxiangyiren** [comment]
@wzshiming   https://github.com/hectorqin/reader/blob/master/docker-compose.yaml

**Pull request merged**
